### ISSUE TITLE
Identify executable that produced a given file

### ISSUE THREAD

**Issue by glatard** [big-data-lab-team/repro-tools#10]
Write a Python function that returns the executable(s) that wrote in a file based on a [reprozip](http://reprozip.org) trace (in sqlite format) of 1 execution.
```
   def get_producers(path_to_reprozip_trace,file_name):
     ...
```
This function will do an SQLITE join query on tables `executed_files` and `opened_files`. Roughly: "find the process ids that opened file `file_name` with mode 2 (write) and get the name of the files executed by these process ids."

Provided that a switch is activated in `verifyFiles.py`, this function could be called on any file for which different runs of the same condition provided different results. This will allow us to identify the executables that created differences within a condition.

**Comment by lalet** [comment]
Done
