### ISSUE TITLE
Metrics filtering from monitor.sh

### ISSUE THREAD

**Issue by lalet** [big-data-lab-team/repro-tools#25]

**Comment by lalet** [comment]
@glatard From the monitor.txt file , we need to identify the differences and write it a separate file ? Is it the filtering which we need to do ?

**Comment by glatard** [comment]
You need to implement a script that will print `1` on stdout when two `monitor.txt` files are considered different, i.e., they differ in places where they are not supposed to, and `0` otherwise.

**Comment by lalet** [comment]
So we need to parse line by line for the keywords and match the values ?
And for intra-run and inter-condition run, the conditions would vary right ?

**Comment by glatard** [comment]
Your script should extract the values we had talked about (#CPUs, CPU model, frequency, etc) and check if they are the same in the two files. This has nothing to do with inter- or intra- condition checks, this is a metric script that will be apply to pairs of `monitor.txt` files.

**Comment by lalet** [comment]
Done
