### ISSUE TITLE
New Matrix (First Action)

### ISSUE THREAD

**Issue by soudabeh19** [big-data-lab-team/repro-tools#35]
[First Action.docx](https://github.com/big-data-lab-team/repro-tools/files/974323/First.Action.docx)

**Comment by glatard** [comment]
Please write this in the issue directly rather than in a word document so that it can be discussed here.

**Comment by soudabeh19** [comment]
In first matrix (Lalet's code) each metric of file1 represents the sum of the difference of  all subjects in pair of defined ‎conditions . In order to facilitate the work on my later algorithm i'm going to build a matrix with metircs which contains the ‎difference of a subject of each file in two different conditions. ‎
To give an example, let's consider the first row of the first matrix, related to file 1, with the conditions pairs of (C1,C2) the ‎cell calculated value is as follow  
‎∑ d ( f1[c1] , f1[c2] )
However, in second matrix for example we will have a cell which just shows the difference of file indicated as 1 in ‎conditions pair  (C1,C2) just for a subject  ‎
d ( f1[c1] , f1[c2] )‎
Actually all the values are calculated in advanced and they need to be arranged in matrix2 ‎

**Comment by glatard** [comment]
You can add an option to the script to return your version of the matrix, e.g., ```--full-differences```.
